import { useMemo, useState } from 'react'
import { Badge } from '../ui/Badge'
import { Chip } from '../ui/Chip'
import { Label } from '../ui/Label'
import { cn } from '../ui/cn'
import { textSamples } from '../../data/run'
import { detectors } from '../../data/run'
import { pct } from '../../lib/format'

/**
 * What the generative layer actually produces.
 *
 * Both columns are machine-written. The pool's not-fraudulent entries carry a
 * generated persona and synthetic merchant and bank names exactly as the
 * fraudulent ones do, so the label separates intent rather than provenance.
 * Calling the left column a real consumer complaint would be false, and the
 * honest question is more interesting anyway: can a text expert separate intent
 * when both sides are generated?
 *
 * Tiers are shown as ordinal labels only. They are ranked, never treated as
 * quantities, because error rates are not comparable across model editions.
 */

const VERTICAL_LABEL: Record<string, string> = {
  friendly_fraud: 'Friendly fraud',
  refund_abuse: 'Refund abuse',
  support_se: 'Support engineering',
}

const TIER_LABEL = ['tier 0', 'tier 1', 'tier 2', 'tier 3']

export function ArtifactInspector() {
  const data = textSamples
  const verticals = useMemo(
    () => [...new Set((data?.samples ?? []).map((s) => s.vertical))],
    [data],
  )
  const tiers = useMemo(
    () => [...new Set((data?.samples ?? []).map((s) => s.tier))].sort((a, b) => a - b),
    [data],
  )

  const [vertical, setVertical] = useState(verticals[0] ?? '')
  const [tier, setTier] = useState(tiers[0] ?? 0)

  if (!data) return null

  const pick = (fraudulent: boolean) =>
    data.samples.find(
      (s) => s.vertical === vertical && s.tier === tier && s.fraudulent === fraudulent,
    )
  const genuine = pick(false)
  const fraudulent = pick(true)
  const textExpert = detectors.experts.find((e) => e.name === 'text')

  return (
    <div>
      <p className="prose-sans max-w-3xl text-[0.9375rem] leading-relaxed text-ink-2">
        Three of the nine verticals put written text in front of a control that reads it. Both
        columns below are generated by {data.generator} and embedded with {data.embed_model}. The
        left column is not a real consumer complaint: it carries a generated persona and synthetic
        merchant and bank names just as the right one does.{' '}
        <span className="text-ink">The label separates intent, not provenance</span>, which makes
        the real question whether a text expert can tell intent apart when both sides are machine
        written.
      </p>

      <div className="mt-4 flex flex-wrap items-center gap-4">
        <div>
          <Label>vertical</Label>
          <div className="mt-1.5 flex flex-wrap gap-1">
            {verticals.map((v) => (
              <button
                key={v}
                type="button"
                onClick={() => setVertical(v)}
                aria-pressed={vertical === v}
                className={cn(
                  'rounded-chip px-2.5 py-1 text-[0.8125rem] transition-colors duration-150',
                  vertical === v
                    ? 'bg-atk/15 text-atk'
                    : 'text-ink-3 hover:bg-surface-hover hover:text-ink-2',
                )}
              >
                {VERTICAL_LABEL[v] ?? v}
              </button>
            ))}
          </div>
        </div>

        <div>
          <Label>capability tier (ordinal)</Label>
          <div className="mt-1.5 flex flex-wrap gap-1">
            {tiers.map((t) => (
              <button
                key={t}
                type="button"
                onClick={() => setTier(t)}
                aria-pressed={tier === t}
                className={cn(
                  'rounded-chip px-2.5 py-1 font-mono text-[0.8125rem] transition-colors duration-150',
                  tier === t
                    ? 'bg-holdout/15 text-holdout'
                    : 'text-ink-3 hover:bg-surface-hover hover:text-ink-2',
                )}
              >
                {TIER_LABEL[t] ?? `tier ${t}`}
              </button>
            ))}
          </div>
        </div>
      </div>

      <div className="mt-5 grid gap-4 lg:grid-cols-2">
        {(
          [
            [genuine, 'genuine intent', 'pass' as const],
            [fraudulent, 'fraudulent intent', 'atk' as const],
          ] as const
        ).map(([sample, heading, tone]) => (
          <div key={heading} className="rounded-panel border border-rule bg-surface">
            <div className="flex items-center justify-between gap-3 border-b border-rule-subtle px-4 py-2.5">
              <Label>{heading}</Label>
              <Badge tone={tone}>generated</Badge>
            </div>
            {sample ? (
              <div className="px-4 py-3">
                <p className="prose-sans text-[0.9375rem] leading-relaxed text-ink">
                  {sample.text}
                </p>

                <div className="mt-4">
                  <Label>persona it was written as</Label>
                  <p className="prose-sans mt-1 text-[0.875rem] text-ink-2">{sample.persona}</p>
                </div>

                {sample.facts && (
                  <div className="mt-4">
                    <Label>facts it was grounded in</Label>
                    <div className="mt-1.5 flex flex-wrap gap-1.5">
                      {Object.entries(sample.facts).map(([k, v]) => (
                        <Chip key={k} tone={tone === 'atk' ? 'atk' : 'pass'}>
                          {k}: {String(v)}
                        </Chip>
                      ))}
                    </div>
                    <p className="prose-sans mt-2 text-[0.8125rem] text-ink-3">
                      The text is grounded in specific facts rather than free-associated, which is
                      what makes it usable as a training signal.
                    </p>
                  </div>
                )}
              </div>
            ) : (
              <p className="px-4 py-6 text-[0.875rem] text-ink-3">
                No sample for this combination.
              </p>
            )}
          </div>
        ))}
      </div>

      <div className="mt-4 rounded-panel border border-rule bg-surface px-4 py-3">
        <p className="prose-sans max-w-3xl text-[0.9375rem] leading-relaxed text-ink-2">
          The text expert carries{' '}
          <span className="text-def">
            {textExpert ? pct(textExpert.normalized_weight) : '4.7%'}
          </span>{' '}
          of combiner weight, the thinnest of the five channels, because text-bearing events are
          the rarest in ordinary traffic. That is the gap the trained attacker converged on, and
          the pool above is the material it converged on using.
        </p>
        <p className="prose-sans mt-2 text-[0.875rem] text-ink-3">
          {data.tier_note} Pool of {data.n_entries.toLocaleString('en-US')} entries, fingerprint{' '}
          <span className="num">{data.fingerprint?.slice(0, 16)}</span>. Embeddings are excluded
          here: they are what make the full pool 86 MB.
        </p>
      </div>
    </div>
  )
}
